language: python
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
cache:
    - pip
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "3.6-dev"
    - "nightly"
    # Python 3.6 is not yet available
    # - "3.6"
    ## cryptography-1.0 is not compatible with PyPy < 2.6.
    ## https://github.com/travis-ci/travis-ci/issues/4756
    # - "pypy"
    # - "pypy3"
install:
    - pip install -r requirements-dev.txt
script:
    - python -m unittest discover
