language: python
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
cache:
    - pip
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "nightly"
install:
    - pip install -r requirements-dev.txt
script:
    - python -m unittest
